media:
  input: posts/img
  output: img
content:
- name: posts
  label: Posts
  type: collection
  path: '_posts'
  view:
    fields: [ title, published, date, author, categories, tags, thumbnail, permalink, layout, description, latex, highlightjs ]
  fields:
  - name: published
    label: Published
    type: boolean
    default: true
    description: "Set to 'true' to publish this post.  If unchecked, the post will be a draft."
  - name: date
    label: Date
    type: date
    options:
      format: yyyy-MM-dd HH:mm
    description: "The date of the post. This is used for sorting and displaying posts chronologically."
    required: true
  - name: date
    label: Date
    type: string
    description: "The date of the post. This is used for sorting and displaying posts chronologically. Format: yyyy-MM-dd HH:mm:ss +0530 . 24 Hour Format. "
  - name: layout
    label: Layout for the Post
    type: string
    description: "The layout template to be used for this post. This should match one of the layout files in your Jekyll site. Use Post Layout for better results."
    required: true
    default: post
  - name: title
    label: Title
    type: string
    description: "The title of the post. Keep it concise and engaging!"
    required: true
  - name: description
    label: Description
    type: string
    description: "The Description of the post. Keep it concise and engaging!"
  - name: author
    label: Author of the Post
    type: string
    description: "The author of the post. This can be the name of the person who wrote the post.Should be matched with _data/authors.yml"
    default: "Prasad"
    required: true
  - name: categories
    label: Categories
    type: string
    description: "Categories for the post. Separate multiple categories with spaces."
  - name: tags
    label: Tags
    type: string
    description: "Tags for the post. Separate multiple tags with spaces."
  - name: latex
    label: Enable LaTeX Supports
    type: boolean
    description: "Enable LaTeX support for mathematical equations and symbols in the post."
    default: false
  - name: highlightjs
    label: Enable highlightJS Supports
    type: boolean
    description: "Enable highlight.js support for syntax highlighting in code blocks within the post. Use <pre><code> for insert code. Make sure inserting code is parsered."
    default: false
  - name: thumbnail
    label: Thumbnail of the Post
    type: string
    description: "The thumbnail image for the post. This image will be displayed as a preview for the post.Should be use relative URL to the root. Use 1:1 image for better results."
    default: "/posts/img/logo.webp"
  - name: permalink
    label: Permalink for the Post
    type: string
    description: "The permalink for the post. This should be a unique URL path for the post, following the specified format for SEO-friendly URLs. For better results, ensure that the permalink follows the format: /posts/:title-:year:month:day_:hour:minute:second:output_ext"
    default: "/posts/:title-:year:month:day_:hour:minute:second:output_ext"
    required: true
  - name: body
    label: Body
    type: rich-text
    description: "The main content of the post. Use Markdown for formatting."
  - name: body
    label: Body (in HTML)
    type: code
    options:
      language: html
    description: "The main content of the post. Use HTML for formatting."
- name: config
  label: Jekyll config
  path: _config.yml
  type: file
  fields:
  - name: title
    label: Website title
    type: string
    description: "The main title of your website. This is used in the browser tab and in some SEO descriptions."
    default: "PrasadM's Blogfolio"
  - name: name
    label: Website Name
    type: string
    description: "Custom Name of the Site. Used in About Me."
    default: "Prasad Madhuranga"
  - name: description
    label: Website description
    type: string
    description: "A short description of your website (around 150-160 characters). This is used in search engine results and social media previews for the homepage."
  - name: url
    label: Website URL
    type: string
    pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
    description: "The full URL of your website (e.g., https://www.example.com). Make sure to include 'https://' if your site uses HTTPS."
  - name: local
    label: Any Name of Location
    type: string
    description: "Location Name that used in About Me."
  - name: jobs
    label: Any Name of Jobs
    type: string
    description: "Job Name that used in About Me."
  - name: slogan
    label: Your Slogan
    type: string
  - name: cover
    label: Preview image
    type: image
    description: "Image used in the social preview on social networks (e.g. Facebook, Twitter...). Choose an image that represents your brand or the content of the page."
  - name: telegram_token
    label: Telegram Bot Token
    type: string
    description: "Telegram Bot Token that used in Contact form"
  - name: telegram_chat_id
    label: Telegram Chat ID
    type: string
    description: "Telegram Chat ID where all messages from Contact form should send."
  - name: linkedin
    label: LinkedIn Profile
    type: string
    description: "Add LinkedIn Profile URL"
  - name: github
    label: GitHub Profile
    type: string
    description: "Add GitHub Profile URL"
  - name: medium
    label: Medium Profile
    type: string
    description: "Add Medium Profile URL"
  - name: telegram
    label: Telegram Profile
    type: string
    description: "Add Telegram Channel URL"
  - name: google-maps
    label: Google Maps Profile
    type: string
    description: "Add Google Maps Profile URL"
  - name: researchgate
    label: Research Gate Profile
    type: string
    description: "Add Research Gate Profile URL"
- name: portfolio
  label: Portfolio
  type: collection
  path: '_portfolio'
  view:
    fields: [ published, date, layout, title, description, tags, latex, highlightjs, thumbnail, permalink, body]
  fields:
  - name: published
    label: Published
    type: boolean
    default: true
    description: "Set to 'true' to publish this portfolio item."
  - name: date
    label: Date
    type: date
    options:
      format: yyyy-MM-dd HH:mm
    description: "The date of the portfolio."
    required: true
  - name: layout
    label: Layout for the Portfolio
    type: string
    description: "The layout template to be used for this portfolio. This should match one of the layout files in your Jekyll site. Use appropiate Layout for better results."
    required: true
    default: post
  - name: order
    label: Number for the Portfolio
    type: number
    description: "Portfolio Number for sorting."
    required: true
  - name: title
    label: Title
    type: string
    description: "The title of the portfolio. Keep it concise and engaging!"
    required: true
  - name: description
    label: Description
    type: string
    description: "The Description of the portfolio. Keep it concise and engaging!"
  - name: categories
    label: Categories
    type: string
    description: "Categories for the portfolio. Separate multiple categories with spaces."
  - name: tags
    label: Tags
    type: string
    description: "Tags for the portfolio. Separate multiple tags with spaces."
  - name: latex
    label: Enable LaTeX Supports
    type: boolean
    description: "Enable LaTeX support for mathematical equations and symbols in the post."
    default: false
  - name: highlightjs
    label: Enable highlightJS Supports
    type: boolean
    description: "Enable highlight.js support for syntax highlighting in code blocks within the post. Use <pre><code> for insert code. Make sure inserting code is parsered."
    default: false
  - name: thumbnail
    label: Thumbnail of the Portfolio
    type: string
    description: "The thumbnail image for the post. This image will be displayed as a preview for the post.Should be use relative URL to the root. Use 1:1 image for better results."
    default: "/posts/img/logo.webp"
  - name: permalink
    label: Permalink for the Portfolio
    type: string
    description: "The permalink for the post. This should be a unique URL path for the post, following the specified format for SEO-friendly URLs. For better results, ensure that the permalink follows the format: /portfolio/:title:output_ext"
    default: "/portfolio/:title:output_ext"
    required: true
  - name: body
    label: Body
    type: rich-text
    description: "The main content of the post. Use Markdown for formatting."
  - name: body
    label: Body (in HTML)
    type: code
    options:
      language: html
    description: "The main content of the post. Use HTML for formatting."