media:
  input: posts/img
  output: posts/img
content:
- name: posts
  label: Posts
  type: collection
  path: '_posts'
  view:
    fields: [ title, published, date ]
  fields:
  - name: published
    label: Published
    type: boolean
    default: true
    hint: "Set to 'true' to publish this post.  If unchecked, the post will be a draft."
  - name: date
    label: Date
    type: date
    hint: "The date of the post. This is used for sorting and displaying posts chronologically."
  - name: title
    label: Title
    type: string
    hint: "The title of the post. Keep it concise and engaging!"
  - name: body
    label: Body
    type: rich-text
    hint: "The main content of the post. Use Markdown for formatting."
- name: config
  label: Jekyll config
  path: _config.yml
  type: file
  fields:
  - name: title
    label: Website title
    type: string
    description: "The main title of your website. This is used in the browser tab and in some SEO descriptions."
  - name: description
    label: Website description
    type: string
    description: "A short description of your website (around 150-160 characters). This is used in search engine results and social media previews for the homepage."
  - name: url
    label: Website URL
    type: string
    pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
    description: "The full URL of your website (e.g., https://www.example.com). Make sure to include 'https://' if your site uses HTTPS."
  - name: cover
    label: Preview image
    type: image
    description: "Image used in the social preview on social networks (e.g. Facebook, Twitter...). Choose an image that represents your brand or the content of the page."
  - name: telegram_token
    label: Telegram Bot Token
    type: string
    description: "Telegram Bot Token that used in Contact form"
  - name: telegram_chat_id
    label: Telegram Chat ID
    type: string
    description: "Telegram Chat ID where all messages from Contact form should send."
  - name: linkedin
    label: LinkedIn Profile
    type: string
    description: "Add LinkedIn Profile URL"
  - name: github
    label: GitHub Profile
    type: string
    description: "Add GitHub Profile URL"
  - name: medium
    label: Medium Profile
    type: string
    description: "Add Medium Profile URL"
  - name: telegram
    label: Telegram Profile
    type: string
    description: "Add Telegram Channel URL"
  - name: google-maps
    label: Google Maps Profile
    type: string
    description: "Add Google Maps Profile URL"
  - name: researchgate
    label: Research Gate Profile
    type: string
    description: "Add Research Gate Profile URL"
