url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: PrasadM # the name of your site, e.g. ACME Corp.
description: A blog about web development, technology, and the latest trends.

telegram_token: "<%= ENV['TELEGRAM_TOKEN'] %>"
telegram_chat_id: "<%= ENV['TELEGRAM_CHAT_ID'] %>"

# plugins:
#   - jekyll-archives

# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: category
#     tag: tag
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tag/:name/'