[build]
  publish = "_site"
  command = """
    ruby -v
    sudo -E gem update --system --no-document
    bundle install
    bundle exec jekyll build
  """

[build.environment]
  RUBY_VERSION = "3.4.2"